apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: boring-media-co
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo  # GCP standard persistent disk 